export const metadata = {
  title: {
    default: 'Home Page',
    template: '%s ++++hello',
  },
  description: 'Generated by create next app',
};

export default function productPage() {
  return <div>This is product1 page</div>;
}
