import Link from 'next/link';
import Gallery from '../GalleryComponent';
import styles from '../page.module.scss';

export const metadata = {
  title: {
    default: 'Home Page',
    template: '%s ++++hello',
  },
  description: 'Generated by create next app',
};

const images = [
  './middleearth1.png',
  './middleearth2.png',
  './middleearth3.png',
];

export default function MiddleEarth() {
  return (
    <div>
      <header className={styles.navbar}>
        <div className={styles.test}>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <img
            src="./shopping-basket.png"
            alt="Shopping cart"
            className={styles.shoppingCart}
          />
        </div>
      </header>

      <div className={styles.productDivMain}>
        <div className={styles.productDivLeft}>
          <div>
            <Gallery images={images} />
          </div>
          <br />
          <hr />
          <br />
          <div className={styles.productDivLeftText}>
            <p>
              Traveling to Middle Earth, a realm of enchantment and legend, is
              an extraordinary journey that immerses you in a world where
              fantasy and history blend seamlessly. Middle Earth, as envisioned
              by J.R.R. Tolkien in his renowned works "The Hobbit" and "The Lord
              of the Rings," is a land of breathtaking landscapes, ranging from
              the serene Shire with its lush, rolling hills and quaint
              hobbit-holes, to the majestic, awe-inspiring peaks of the Misty
              Mountains.
            </p>
            <br />
            <p>
              Your adventure begins the moment you set foot into this mystical
              land. As you traverse through Middle Earth, you'll encounter vast,
              ancient forests like Lothlórien, home to the ethereal Elves, where
              golden leaves create a perpetual autumn, and the air is filled
              with an enchanting melody. The great Elven city of Rivendell,
              nestled in the foothills of the mountains, offers a sanctuary of
              peace and wisdom, a stark contrast to the foreboding realm of
              Mordor, with its volcanic landscapes and the ever-watchful eye of
              Sauron.
            </p>
          </div>
        </div>
        <div className={styles.productDivRight}> </div>
      </div>
    </div>
  );
}
