export const metadata = {
  title: {
    default: 'Home Page',
    template: '%s hello',
  },
  description: 'Generated by create next app',
};

export default function AboutPage() {
  return <div>This is about page</div>;
}
