export const metadata = {
  title: {
    default: 'Home Page',
    template: '%s ++++hello',
  },
  description: 'Generated by create next app',
};

export default function MiddleEarth() {
  return (
    <div>
      <h1>Welcome to About page</h1>
      {}
    </div>
  );
}
