export const metadata = {
  title: {
    default: 'animals',
    template: '%s hello',
  },
  description: 'Generated by create next app',
};

export default function AnimalsPage() {
  return <div>This is animals page</div>;
}
